#!/usr/bin/env python
"""Compile PBMC10k / LINGER-Cistrome results into summary tables.

Re-scores every saved eval_scores.npz with src/benchmarks/pbmc_eval.py (LINGER's
bm_trans semantics) over each candidate space (expressed; linger_tg once the
LINGER re-run has written <root>/linger/tg_<ct>.txt), so all methods are scored
over identical genes. Seeds are averaged per dataset first; the headline number
is the mean over the 19 datasets of LINGER Table S7.

Usage:
  python scripts/29_pbmc_compile.py --root $PBMC_ROOT [--out results/pbmc_summary]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from src.benchmarks import pbmc_eval as pe                  # noqa: E402
from src.utils.io import load_config, load_json, save_json  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(REPO / "configs/pbmc/benchmark.yaml"))
    ap.add_argument("--root", default=os.environ.get("PBMC_ROOT", "data/pbmc"))
    ap.add_argument("--out", default=None, help="default <root>/summary")
    args = ap.parse_args()
    dcfg = load_config(args.config)
    root = Path(args.root)
    out = Path(args.out) if args.out else root / "summary"
    out.mkdir(parents=True, exist_ok=True)
    gt = pe.load_groundtruth(dcfg, root)
    rows, internal = [], []
    for ct in dcfg["cell_types"]:
        pdir = root / "processed" / ct
        if not (pdir / "gene_index.json").exists():
            continue
        gi = load_json(pdir / "gene_index.json")
        genes = [g for g, _ in sorted(gi.items(), key=lambda x: x[1])]
        for f in sorted((root / "results" / ct).rglob("eval_scores.npz")):
            rel = f.parent.relative_to(root / "results" / ct).parts   # source/regime/method[/seedN]
            src, reg, method = rel[0], rel[1], rel[2]
            seed = int(rel[3][4:]) if len(rel) > 3 else 0
            z = np.load(f)
            S = {str(t): z["scores"][k].astype(np.float32) for k, t in enumerate(z["tfs"])}
            chip = pe.evaluate_chip(S, genes, ct, gt, dcfg, root)
            for space, rs in chip["per_dataset"].items():
                for r in rs:
                    rows.append({"method": method, "source": src, "regime": reg, "seed": seed, "space": space,
                                 "cell_type": ct, "id": r["id"], "tf": r["tf"], "in19": r["in_linger_table"],
                                 "auc": r["auc"], "aupr_ratio": r["aupr_ratio"]})
            m = load_json(f.parent / "metrics.json")
            if m.get("internal_test"):
                internal.append({"method": method, "source": src, "regime": reg, "seed": seed, "cell_type": ct,
                                 **m["internal_test"], "epochs": m.get("epochs_run"),
                                 "best_val_aupr": m.get("best_val_aupr")})
    if not rows:
        raise SystemExit("no results found")
    df = pd.DataFrame(rows)
    df.to_csv(out / "per_dataset_per_seed.tsv", sep="\t", index=False)
    key = ["method", "source", "regime", "space"]
    per_ds = df.groupby(key + ["cell_type", "id", "tf", "in19"]).agg(
        auc=("auc", "mean"), aupr_ratio=("aupr_ratio", "mean"), n_seeds=("seed", "nunique")).reset_index()
    per_ds.to_csv(out / "per_dataset.tsv", sep="\t", index=False)
    # headline: per seed, mean over the 19 datasets; then mean +- std over seeds
    d19 = df[df.in19]
    seedmeans = d19.groupby(key + ["seed"]).agg(auc=("auc", "mean"), aupr_ratio=("aupr_ratio", "mean"),
                                                n=("id", "nunique")).reset_index()
    summ = seedmeans.groupby(key).agg(auroc_mean=("auc", "mean"), auroc_std=("auc", "std"),
                                      aupr_ratio_mean=("aupr_ratio", "mean"),
                                      aupr_ratio_std=("aupr_ratio", "std"),
                                      n_datasets=("n", "max"), n_seeds=("seed", "nunique")).reset_index()
    summ = summ.sort_values(["space", "auroc_mean"], ascending=[True, False])
    summ.to_csv(out / "summary.tsv", sep="\t", index=False)
    if internal:
        pd.DataFrame(internal).groupby(["method", "source", "regime"]).mean(numeric_only=True).to_csv(
            out / "internal_test.tsv", sep="\t")
    lines = ["# PBMC10k / LINGER-Cistrome summary (auto-generated by scripts/29)", "",
             "Mean over LINGER Table S7's 19 datasets; mean +- std over seeds.", "",
             "| space | method | source | regime | AUROC | AUPR ratio | datasets | seeds |",
             "|---|---|---|---|---|---|---|---|"]
    for _, r in summ.iterrows():
        lines.append(f"| {r.space} | {r.method} | {r.source} | {r.regime} | {r.auroc_mean:.4f} +- "
                     f"{0 if np.isnan(r.auroc_std) else r.auroc_std:.4f} | {r.aupr_ratio_mean:.3f} | "
                     f"{r.n_datasets} | {r.n_seeds} |")
    lines += ["", "Published (LINGER Table S7, its own candidate genes):"]
    for k, v in dcfg["targets"].items():
        lines.append(f"- {k}: AUROC {v['auroc_mean']}, AUPR ratio {v['aupr_ratio_mean']}")
    (out / "summary.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
